@echo off

start	Chrome-001	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-002	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-003	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-004	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-005	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-006	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-007	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-008	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-009	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-010	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-011	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-012	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-013	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-014	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-015	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-016	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-017	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-018	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-019	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-020	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-021	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-022	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-023	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-024	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-025	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-026	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-027	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-028	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-029	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-030	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-031	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-032	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-033	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-034	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-035	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-036	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-037	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-038	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-039	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-040	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-041	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-042	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-043	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-044	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-045	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-046	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-047	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-048	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-049	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-050	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-051	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-052	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-053	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-054	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-055	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-056	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-057	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-058	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-059	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-060	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-061	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-062	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-063	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-064	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-065	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-066	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-067	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-068	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-069	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-070	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-071	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-072	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-073	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-074	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-075	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-076	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-077	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-078	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-079	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-080	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-081	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-082	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-083	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-084	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-085	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-086	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-087	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-088	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-089	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-090	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-091	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-092	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-093	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-094	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-095	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-096	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-097	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-098	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-099	--incognito	https://youtu.be/FRzGUgco-tE
start	Chrome-100	--incognito	https://youtu.be/FRzGUgco-tE